function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 17-Nov-2020 21:00:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Marker','.','LineStyle','none','Color','none',...
    'Parent',axes1);
set(plot1(1),'DisplayName','0 to 0.2 microns');
set(plot1(2),'DisplayName','0.4 to 0.6 microns');
set(plot1(3),'DisplayName','0.8 to 1 microns');
set(plot1(4),'DisplayName','1.2 to 1.4 microns');
set(plot1(5),'DisplayName','1.6 to 1.8 microns');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',axes1);
set(plot2(1),'DisplayName','0.2 to 0.4 microns','Color',[1 0 0]);
set(plot2(2),'DisplayName','0.6 to 0.8 microns','Color',[0.9 0 0.1]);
set(plot2(3),'DisplayName','1 to 1.2 microns','Color',[0.8 0 0.2]);
set(plot2(4),'DisplayName','1.4 to 1.6 microns','Color',[0.7 0 0.3]);
set(plot2(5),'DisplayName','1.8 to 2 microns','Color',[0.6 0 0.4]);
set(plot2(6),'DisplayName','fitted curve','Color',[0.5 0 0.5]);
set(plot2(7),'DisplayName','fitted curve','Color',[0.4 0 0.6]);
set(plot2(8),'DisplayName','fitted curve','Color',[0.3 0 0.7]);
set(plot2(9),'DisplayName','fitted curve','Color',[0.2 0 0.8]);
set(plot2(10),'DisplayName','fitted curve',...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create ylabel
ylabel({'y'},'FontName','Algerian');

% Create xlabel
xlabel({'x'},'FontName','Algerian');

% Create title
title('Overlayed Parallel Velocity Distributions');

hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Algerian');
% Create legend
legend(axes1,'show');

